### ISSUE TITLE
Example code segfaults in Python3(.6.3)

### ISSUE THREAD

**Issue by Novermars** [kormilitzin/the-signature-method-in-machine-learning#1]
On my system, the code
```
import numpy as np
import esig.tosig as ts
X_1 = np.array([1., 3., 5., 8.])
X_2 = np.array([1., 4., 2., 6.])
two_dim_stream = np.array(zip(X_1, X_2))
signatures = ts.stream2sig(two_dim_stream, 2)
print(signatures) #adjusted for python3
```
Produces a segmentation fault. Funnily enough it runs fine under gdb and gives the proper/expected output. Valgrind shows lots of invalid reads of size 4, which is weird since the underlying data type should be of size 8 (double precision) if I read the Python docs correctly, but does not give any other useful information.

My system: 
1. Python 3.6.3
2. GCC 7.2.0
3. Boost 1.62
4. Numpy 1.14.2
5. Ubuntu 17.10 (downloaded and installed in a VM today)

It's probably a problem of the underlying C++ code and so out of your hands, but just wondering if you can reproduce the problem. I am not very familiar with Python, but maybe the problem is in the change between Python 2 and 3

**Comment by Novermars** [comment]
Alright, did something that I should've done before making this issue: It works perfectly on Python2.7.14. So I'll take the issue to the E-sig people.

Maybe you can add a warning that it doesn't work with Python 3?

**Comment by kormilitzin** [comment]
@Novermars many thanks for reporting this problem. That's strange, as it has been tested on Python 3. I will have a look at the problem.

**Comment by terrylyons** [comment]
Hi, I just ran your code, and indeed it seg faults, however, the reason is that you are not creating the numpy array you think you are. In python 3 it reports shape empty. The trouble is there even with the last two lines commented out.
``

**Comment by kormilitzin** [comment]
While it did work in Python 2, in your case simply change the way you create the 2-dim array:

```
import esig.tosig as ts
X_1 = np.array([1., 3., 5., 8.]).reshape((-1,1))
X_2 = np.array([1., 4., 2., 6.]).reshape((-1,1))
two_dim_stream = np.append(X_1,X_2, axis=1)
```

Just tested and it worked. Let me know if you have any other issues.

**Comment by Novermars** [comment]
And I can confirm from my end that it works! Thanks for the quick reaction! 

And if you a need someone to help you out with this page, just give me a heads up. My machine learning knowledge is work in progress, but after writing my bachelor thesis on rough ODEs (more precisely just the first chapter of @terrylyons excellent book from Saint-Flour summer school (many thanks!)) and reading/learning how powerful signatures are in the context of machine learning, it's something that I've become interested in.

Let me know!

**Comment by kormilitzin** [comment]
Great, thank you for letting me know. It would be highly appreciated if you could demonstrate how you use the ESig package in your machine learning pipelines. For example, you can use the data from the [UCI repository](https://archive.ics.uci.edu/ml/index.php) or Kaggle to practise ML with the signature and then share your code. Learning from your example will help the community to grasp the idea and work out examples and problems.
